server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    username: 'postgres'
    password: '17022001nam'
    url: jdbc:postgresql://localhost:5432/customer
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'



#  spring.datasource.url=jdbc:postgresql://localhost:5432/customer
#  spring.datasource.username=postgres
#  spring.datasource.password=17022001nam
#  spring.jpa.hibernate.ddl-auto= create
#  spring.jpa.show-sql=true
#  spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#  spring.jpa.properties.hibernate.format_sql=true
#  server.error.include-message=always
#  spring.application.name=customer
#  server.port=8080