services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 17022001nam
      PGDATA: /data/postgres
    volumes:
      - postgres: var/lib/postgres/data
    ports:
      - "5432: 5432"
    restart: unless-stopped

volumes:
  postgres: